### ISSUE TITLE
ArgumentNullException is thrown if no log messages are found

### ISSUE THREAD

**Issue by emresebat** [meriturva/Hangfire.Dashboard.JobLogs#1]
Hi Diego

I'm using version 1.3.2 with dotnet 6 and if I check a job detail which didn't produce any logs I see this output

![image](https://github.com/meriturva/Hangfire.Dashboard.JobLogs/assets/2254943/531676a4-8950-4971-aff4-b86dcbe87dc6)

The problem is [here](https://github.com/meriturva/Hangfire.Dashboard.JobLogs/blob/70d29fab7628c06b2c1b415f8fd794b530ebdb02/Hangfire.Dashboard.JobLogs/GlobalConfigurationExtensions.cs#L21) logMessages can be null.

Also if you check the screenshot the error itself is rendered twice, I had to add a MemoryCache to avoid this. 

I'll submit a PR for today.

**Comment by meriturva** [comment]
Thanks @emresebat .
Exception fixed on version 1.3.3

About rendered twice I didn't find a way to reproduce it on normal flow.

Could you please check again on your side and in case open a new issue?

Thanks again.
